### ISSUE TITLE
December 2016 VJump Cards

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#77]
**Maximum Crisis**
- [x] MACR-JP017 - Supreme King Gate Zero --覇王門零
- [x] MACR-JP018 - Supreme King Gate Infinity --覇王門無限
- [x] MACR-JP019 - Supreme King Servant Dragon Darkvrm --覇王眷竜ダークヴルム
- [x] MACR-JP028 - Spiral, the Mythic Radiance Dragon --幻煌龍 スパイラル
- [x] MACR-JP039 - Supreme King Dragon Zarc --覇王龍ズァーク
- [x] MACR-JP056 - Pacifis, City of Mythic Radiance --幻煌の都 パシフィス
- [x] MACR-JP057 - Spiral Crash of the Mythic Radiance Dragon --幻煌龍の螺旋突
- [x] MACR-JP058 - Spiral Hold of the Mythic Radiance Dragon --幻煌龍の螺旋絞
- [x] MACR-JP072 - Clashing Whirlpool of the Mythic Radiance Dragon --幻煌龍の戦禍
- [x] MACR-JP073 - Deep Whirlpool of the Mythic Radiance Dragon --幻煌龍の浸禍

**Premium Pack 19**
- [x] PP19-JP004 - Pendulum Fusion --ペンデュラム・フュージョン

**20th Anniversary Pack**
- [x] 20AP-JP001 - Passionate Duelists --熱き決闘者たち
- [x] 20AP-JP053 - Cosmic Flare --シューティング・ソニック
- [x] 20AP-JP056 - Light Wing Shield --ムーンバリア
- [x] 20AP-JP059 - Spiral Flame Strike --螺旋のストライクバースト

**Errata Cards**
- [x] 20AP-JP??? - Brain Control --洗脳－ブレインコントロール
- [x] 20AP-JP??? - Imperial Order --王宮の勅命
- [x] 20AP-JP??? - Future Fusion --未来融合－フューチャー・フュージョン
- [x] 20AP-JP??? - Rescue Cat --レスキューキャット
- [x] 20AP-JP??? - Brionac, Dragon of the Ice Barrier --氷結界の龍 ブリューナク
- [x] 20AP-JP??? - Goyo Guardian --ゴヨウ・ガーディアン

**Comment by EerieCode** [comment]
I'm not entirely sure "Pendulum Fusion" is doable at the moment: as far as I know, the system doesn't register Spells and Traps as valid Fusion Materials. It's the reason the "Metalfoes" Fusion Monsters require customized procedures. I think a core update might be needed for that one.

**Comment by EerieCode** [comment]
I've added [Spiral, the Mythic Radiance Dragon](http://yugioh.wikia.com/wiki/Spiral,_the_Mythic_Radiance_Dragon) to the list. I know that as a Normal monster it doesn't require a script, but since the Equip Spells refer to it by name, I figured it'd be helpful to have  areminder of its card number in the list. It should be 100912028, correct?

**Comment by SharkYGOPRO** [comment]
Waiting for the Supreme King Dragon Zarc, great job ^;^

**Comment by BlackBallista** [comment]
To prevent Issue clutter, I will put my bug reports in this post, so we can keep track of all problems here.

* Supreme King Servant Dragon Darkvrm (100912019) cannot activate its effect to special summon itself from the grave. No red text present

* Supreme King Gate Infinity (100912018) could not be set as a pendulum scale and none of its effects could be activated. The ability to be set as a scale could be related to the way the sql entry marks the scale (We used the decimal value for "level" equivalent to a level 7 monster with 13/13 scales). In any case, error text popped up: 

![](http://i.imgur.com/FhmU8Zc.jpg)

* Similarly, Supreme King Gate Zero (100912017) could not be set as a pendulum scale and none of its effects could be activated. For this card we simply set the value of the sql entry to "7" because all cards have a default 0 scale and that could be the reason it cant be used as a scale. Error text was present

![](http://i.imgur.com/PVzqzVz.jpg)

* Pendulum Fusion (100214004) cannot be activated, even when legal targets are on the field (the card is not trying to fuse from the pendulum zones) error text present:

![](http://i.imgur.com/PMEkElB.jpg)

*  Number 39 Utopia (84013237) can activate his effect, but an error comes up whenever the material is about to detach, the effect goes through and the material is not detached. Red text present

![](http://i.imgur.com/pgbIF92.jpg)

**Comment by EerieCode** [comment]
The Supreme King cards should be fine now, and I'm working on altering the Utopia move card so that it won't require altering the original scripts. Pendulum Fusion is more complicated, if anyone else knows what's wrong with it it'd be really helpful!

**Comment by EerieCode** [comment]
"Light Wing Shield" has also been updated: remove the updated "Utopia" cards and everything should be fine.

**Comment by SharkYGOPRO** [comment]
EerieCode , The Zarc Dragon to fix ?

**Comment by BlackBallista** [comment]
Supreme King Gate Zero (100912017) cannot activate its effect to destroy itself and Infinity to search for a "fusion" card. No error text

**Comment by EerieCode** [comment]
Zero should be fine now, thanks!

**Comment by destdev** [comment]
oh great, I have hardly any time for one day and miss out all the action >.<
if there are no objections I'll grab at least those 3 remaining Mythic Dragon cards and do at least something^^

**Comment by EerieCode** [comment]
No problem, go ahead! I'm trying to do Passionate Duelists in the meantime, and I'll further update Zarc's procedure once I return home: after that, the only thing left will be figuring out why "Pendulum Fusion" doesn't work.

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-scripts/blob/master/utility.lua#L1099
almost all fusion monsters check `Card.IsCanBeFusionMaterial`, which disallow spell and traps as default.
so i dont know how to make _Pendulum Fusion_ work

**Comment by EerieCode** [comment]
Mmh... How about altering the function IsCanBeFusionMaterial through "Pendulum Fusion", so that it sets _true_ as the default when the card is in the Pendulum Zone? This way the changes would affect all other cards without us needing to change them all manually

**Comment by EerieCode** [comment]
I've updated a patch using [the manga version of "Pendulum Fusion"](https://raw.githubusercontent.com/Ygoproco/Live2016/master/script/c511002981.lua) @MichaelLawrenceDee made for Percy. Can you try it and see if it works?

**Comment by mercury233** [comment]
it work for me, thanks

**Comment by EerieCode** [comment]
Only partially related to VJump, but since "[Gandora Giga Rays](http://yugioh.wikia.com/wiki/Gandora_Giga_Rays_the_Dragon_of_Destruction)" is already out, does that mean that the official "Gandora" setcode is going to be 0xf5?

**Comment by nekrozar** [comment]
http://vjump.shueisha.co.jp/nextinfo/
Gandora Giga Rays has not been on sale yet.

**Comment by SharkYGOPRO** [comment]
How do I add token? Mythic Radiance Dragon Token

**Comment by destdev** [comment]
the same way you add any other card
tokens don't have scripts, you just add them like any other regular normal monsters, just with an added token type (value 0x4000)

**Comment by SharkYGOPRO** [comment]
(value 0x4000) is Mythic Radiance Dragon Token?

**Comment by destdev** [comment]
no, that's the value for the type token
I don't know in what way you add your cards, if you know how to add regular normal monsters just do the same with that token. Only on the type column you need to add a value of 0x4000. (I just noticed on the guide of percys forum from michael he seems to have forgotten to note that value on the type spoiler)

**Comment by SharkYGOPRO** [comment]
I add by the dataeditorX, if you have another better program could tell me, I tried in several ways and I could not
![screenshot_2](https://cloud.githubusercontent.com/assets/24573510/21238636/e9ef8e16-c2ea-11e6-9b2e-6af24d0dcc0e.png)

**Comment by BlackBallista** [comment]
Cosmic Flare's (100213053) effect to shufflea monster at the beggining of the damage step is not activating. The battle simply continues as normal. error text present

![](http://i.imgur.com/mkytwGn.jpg)

**Comment by destdev** [comment]
there must be a token checkbox in the card type section... if not this editor must be missing that^^
I usually use devpros card manager, that one definitly has that. I think buttys also put on a version of the card manager somewhere in the percy forums.

for that cosmic flare problem: should be fixed now

**Comment by BlackBallista** [comment]
The effect of Deep Whirlpool of the Mythic Radiant Dragon (100912073) to reduce ATK/DEF and negate effects cant be activated either from the hand or the field. Maybe something in the condition is wrong?No error text is present

**Comment by BlackBallista** [comment]
Furthermore, its effects to equip cards from Hand/grave also cannot be activated. Error text is present

![](http://i.imgur.com/BpmVawx.jpg)

**Comment by destdev** [comment]
yea, I screwed up the target, it targeted the wrong side of the field^^
and the g error should also be gone now

**Comment by SharkYGOPRO** [comment]
Hi, it looks like Dragon King Zarc is still not working, please you can try to work a little more on it

**Comment by BlackBallista** [comment]
SharkYGOPro, what do you mean its not working, you cant summon it?

**Comment by SharkYGOPRO** [comment]
Yes, I tried with the polymerization and with the effects of the MAgicians and I could not

**Comment by SharkYGOPRO** [comment]
BlackBallista, You were able to summon?

**Comment by BlackBallista** [comment]
Yes. I was able to summon Zarc by using gale dogra and dragons mirror. Your issue is probably the fact that astrograph sorcerer and Cronograph sorcerer are using the wrong setcodes/Zarc ID

**Comment by SharkYGOPRO** [comment]
What setcode did you add on the Zarc and the magicians?

**Comment by destdev** [comment]
you can summon him, however there is an issue if you want to use 2 xyz/pendulum or 2 synchro/pendulum monsters, that has to be resolved

**Comment by SharkYGOPRO** [comment]
Can you see what's wrong with the cards?
![screenshot_5](https://cloud.githubusercontent.com/assets/24573510/21244984/4acdf72e-c307-11e6-8460-50229842d3fa.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/24573510/21244986/4ad25242-c307-11e6-8e79-3050fdd13e8f.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/24573510/21244985/4acef0d4-c307-11e6-8a4d-89dcae76c528.png)

**Comment by destdev** [comment]
uh ... it might be that the current translation is a bit off I guess?
currently it is scripted to use monsters with the type dragon + xyz/synchro/fusion/pendulum, not the respective setcodes ... there might be something

**Comment by SharkYGOPRO** [comment]
A question, is it possible to invoke the Zarc using the magicians who are treated as Dragon Fusion / Synchro / Pendulum Xyz?

**Comment by destdev** [comment]
not with the current script, there you must use the respective monster types, like the current translation suggests, not the xyz-/synchro-/fusion-/pendulumdragon archtypes

**Comment by destdev** [comment]
we might have found the issue with the summoning method used by the sorcerers, I'll just quote myself from the chat here:
c:IsFacedown() ... servers have a huge problem with that function in the extradeck
they don't recognize that, this has already been an all time problem with sea castle also
change that to "not c:IsFaceup()" and it should work
[...]
I really have no idea why, it always bugs out on that on the server only, it works fine lokal
for whatever reason on the server it refuses to recognize the facedown function for the extra deck

**Comment by mercury233** [comment]
i don't have time to test but a got a bug report saying _Stardust Warrior_ can activate effect with no cost.

**Comment by EerieCode** [comment]
I'll upload Zarc's updated procedure in an hour. Sorry, I forgot to put it on Fluoro as well :P

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/21260781/91285e6a-c3c2-11e6-81d5-ec08fcdd65c4.png)

Zarc show error when being summoned by _Miracle Synchro Fusion_.

Replay: https://puu.sh/sRoUO/982a5389f2.yrp
or enter this to watch it online
![image](https://cloud.githubusercontent.com/assets/13391795/21260832/c12bad9c-c3c2-11e6-9bb2-65ab1e897cb6.png)

**Comment by destdev** [comment]
seems like you can use 4 extra deck monsters with odd-eyes fusion for the summon of Zarc Oo

**Comment by mercury233** [comment]
because Zarc don't have `check_fusion_material_48144509` and `select_fusion_material_48144509`

**Comment by nekrozar** [comment]
> http://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=12007
> 相手フィールドにモンスターが２体以上存在し、**自分フィールドにモンスターが存在しない場合**、自分のエクストラデッキの「オッドアイズ」モンスターも**２体まで融合素材とする事ができる**。 
> If your opponent controls 2 or more monsters and **you control no monsters**, you can also **use up to 2 "Odd-Eyes" monsters in your Extra Deck as Fusion Materials**.

So Zarc cannot Fusion Summon by _Odd-Eyes Fusion_.

**Comment by mercury233** [comment]
you should can fusion it normally without using the extra material.

**Comment by destdev** [comment]
I mean, the game currently allows that for whatever reason, I know that's an error.
Just a `check_fusion_material_48144509` function that returns false should be enough to solve that problem.

While trying to reproduce the problem from the picture above I encountered another one: While using miracle synchro fusion you can summon zarc by banishing 3 xyz/pendulum dragons (3 odd-eyes rebellion/raging dragons in this case)

**Comment by EerieCode** [comment]
I'm already aware of all of these issues, and I'm already planning to give Zarc's procedure an overhaul to fix them tomorrow: for now, though, there's not much I can do, this si too complex to fix on the fly. I'm seriously considering using this as a base to make something like Auxiliary.AddFusionProcFunMulti() for the utilities, just so we can avoid something like this in the future...

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/21298607/512d274c-c5ce-11e6-9662-3056cb020172.png)
@EerieCode I can't fusion Zarc with those cards on field.

**Comment by destdev** [comment]
should be fixed now, there was an else statement missing at the end

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/21348692/3d16c92c-c6e9-11e6-96af-147fe02f6460.png)
I got a infinite loop with those cards on field and hand. This error keep coming out, stuck the game.

**Comment by EerieCode** [comment]
Can you try again? I think it should be fine now

**Comment by mercury233** [comment]
![image](https://cloud.githubusercontent.com/assets/13391795/21356198/b47d5338-c70b-11e6-880a-c506bc2e42af.png)
the problem still exists

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/c5edb6431928d5c34f0aa85f56bc34d21e6f3fe4
I guess it is fixed, by a simple test.
